query {
   allDevices{
    edges{
      node{
        id
        idUser
        addressip
        typedevice
        osversion
        user{
          firstname
          lastname
          username
          role
          devices {
            edges {
              node {
                id
              }
            }
          }
        }
        
      }
    }
  
  }
}